#!/usr/bin/env python3

SEED = 'velvet lymph giddy number token physics poetry unquoted nibs useful sabotage limits benches lifestyle eden nitrogen anvil fewest avoid batch vials washing fences goat unquoted'
SECOND_SEED = 'peeled mixture ionic radar utopia puddle buying illness nuns gadget river spout cavernous bounced paradise drunk looking cottage jump tequila melting went winter adjust spout'
THIRD_SEED = 'dilute gutter certain antics pamphlet macro enjoy left slid guarded bogeys upload nineteen bomb jubilee enhanced irritate turnip eggs swung jukebox loudly reduce sedan slid'

MAIN_ADDRESS = 'C4KFgKxtSdc4886T7196doS9GPMzexD9gXpsZJDwVjeRVdFCSoHnv7KPbBeGpzJBzHRCAs9UxqeoyFQMYbqSWYTfJHn8Rtc'
SECOND_MAIN_ADDRESS = 'C5ytcpAyJ93RDV5aAhLJzQCjDz2ViLRduE3ijDZu3osWKBjMGkV1XPk4pfDUMqt1Aiezvephdqm6YD19GKFD9ZcXVXJiCsG'
THIRD_MAIN_ADDRESS = 'C8WMTHkL7bVBUMhuykdK3gQ98XDqDTYW1hNLaXNvjpsJaSbNtdXh1sKMsdVgqkaihChAzEy29zEDPMR3NHQvGoZCLByoHBW'
MAIN_ADDRESS_BAD_CHECKSUM = 'C4KFgKxtSdc4886T7196doS9GPMzexD9gXpsZJDwVjeRVdFCSoHnv7KPbBeGpzJBzHRCAs9UxqeoyFQMYbqSWYTfJHn8Rtd'
MAIN_INTEGRATED_ADDRESS = 'CDcixfvMenj25WooY4BVmgdcKwZu5EksVZSZkDd6ooxSVVqQ4ubxXkhLF6hEqtw96i9cf3cVfLw8UWe95bdDKfRQeYtPwLm1Jiw7BGQ2SC'
MAIN_INTEGRATED_ADDRESS_PAYMENT_ID_0123456789ABCDEF = 'CE1vh8nP3u84886T7196doS9GPMzexD9gXpsZJDwVjeRVdFCSoHnv7KPbBeGpzJBzHRCAs9UxqeoyFQMYbqSWYTfSbLRB61BQVATy8cp1E'
SECOND_MAIN_INTEGRATED_ADDRESS_PAYMENT_ID_1122334455667788 = 'CFgZdczTuQZRDV5aAhLJzQCjDz2ViLRduE3ijDZu3osWKBjMGkV1XPk4pfDUMqt1Aiezvephdqm6YD19GKFD9ZcXjANAhztPi9cGPBrytB'
ACCOUNT_1_BASE = 'HQ63uKXdYjb3LUMssBCumk3MfyEsFqLAaGDf6oxddu61EgSFzt8gCwUD4tr3kp9TUfdPs2CnpD7xLZzyC1Ei9UsW3nMfQ8Q'
ACCOUNT_2_BASE = 'HYuFtHpeQgtbkvaBnG7vYP6DCNneLWcXqNmfPmyyDkavAUUgrHQEAhTNK3jEq69kGPDrd3i5inPivCwTvvA12eQ4SNzvnEZ'
ACCOUNT_0_SUB_1 = 'HRg6FkSZUMpU3NN1VpFRndSukeyEb3Xpv8qZjjsoJZnTYpDYceuUTpog13D7qPxpviS7J29bSgSkR11hFFoXWk2yNZ5c5xi'
ACCOUNT_1_SUB_1 = 'HV7eabMCHbUikVBmG1TaP1KumZ3hB3Q5f4wZRjuppNdwYjWzs2RgbLYQgtpdu2YdoTT3EZhiUGaPJQt2FsykeFZbCrDusMe'
ACCOUNT_1_SUB_2 = 'HUbLTfQkHQ3D3Frefqnrqif11TjVsTPaTcp37kqqKMrdDRUhpJRczeR7KiBmSHF32UJLP3HHhKUDmEQyJrv2mV8yFCFpvuB'
ACCOUNT_0_SUB_999 = 'HYfzTfJ4tHhP14AKnZUBwnXWj46MuNmLvHfPTpmry52DbfNjjHVvHUk4mczU8nj8yZ57zBhksTJ8kM5xKeJXw55kCNTp1XP'

TESTNET_ADDRESS = 'PkRG8ZRWvXzjdsemFMGb5MQ3dYEjQ1oM8harGpqiYbKBg2eTRse2TWUau1SQYsuHzBNwkakRQnja4PmUECatMRHp1Yt3H5Dqx'
STAGENET_ADDRESS = 'FRNMhEvp8w2eJ1REzGMAat1ZeHvuajvDiXqboEocPaDRRmqWoVPzy46GLo866qRFjbNhfkNckyhST3WEvBviDwpUDaG5Wtr'
